config:
  credentials: []
  project_repos:
    bitbucket.org/cessda/cessda.cdc.searchkit/src/master:
      branch: master
      repo: https://bitbucket.org/cessda/cessda.cdc.searchkit/src/master
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-goldenrod-stoat.sh
        container: qc.acc_stealthy-azure-gerbil
  QC.Doc:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-goldenrod-goose.sh
        container: qc.doc_freaky-orange-duck
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master git:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-saffron-angelfish.sh
        container: qc.doc_sleepy-khaki-barracuda
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-wisteria-oyster.sh
        container: qc.doc_smelly-thistle-ibis
  QC.Lic:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-myrtle-budgerigar.sh
        container: qc.lic_tasty-crimson-monkey
  QC.Sty:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-black-tamarin.sh
        container: qc.sty_scanty-tangerine-cattle
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-cerise-ladybird.sh
        container: qc.sty_droopy-amber-gopher
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master stylelint:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-violet-hare.sh
        container: qc.sty_snoopy-cerulean-mayfly
  QC.Ver:
    repos:
      bitbucket.org/cessda/cessda.cdc.searchkit/src/master get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-mustard-tzu.sh
        container: qc.ver_flaky-rose-lemur
timeout: 5400
